// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-FYfOtkvf93qKc65XgUmTj2AAYW4X8b4',
    appId: '1:675740561770:web:021fd50220fe7c50ec3513',
    messagingSenderId: '675740561770',
    projectId: 'careloop-b1c86',
    authDomain: 'careloop-b1c86.firebaseapp.com',
    storageBucket: 'careloop-b1c86.firebasestorage.app',
    measurementId: 'G-VWK06EB2YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJzVuAPt6X7opuJV3YHfnFQcK9HLgXzUU',
    appId: '1:675740561770:android:ecb20a4557ead217ec3513',
    messagingSenderId: '675740561770',
    projectId: 'careloop-b1c86',
    storageBucket: 'careloop-b1c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlMFIKh8wRZjyIPoLCB7xIvta4LyHQjHA',
    appId: '1:675740561770:ios:92af53b716d8b023ec3513',
    messagingSenderId: '675740561770',
    projectId: 'careloop-b1c86',
    storageBucket: 'careloop-b1c86.firebasestorage.app',
    iosBundleId: 'com.example.careloop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlMFIKh8wRZjyIPoLCB7xIvta4LyHQjHA',
    appId: '1:675740561770:ios:92af53b716d8b023ec3513',
    messagingSenderId: '675740561770',
    projectId: 'careloop-b1c86',
    storageBucket: 'careloop-b1c86.firebasestorage.app',
    iosBundleId: 'com.example.careloop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-FYfOtkvf93qKc65XgUmTj2AAYW4X8b4',
    appId: '1:675740561770:web:dd8edfc95e0ecf39ec3513',
    messagingSenderId: '675740561770',
    projectId: 'careloop-b1c86',
    authDomain: 'careloop-b1c86.firebaseapp.com',
    storageBucket: 'careloop-b1c86.firebasestorage.app',
    measurementId: 'G-1X4BQFWJXD',
  );
}
